//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerPointArrangeAddin.Ribbon {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ArrangeRibbonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ArrangeRibbonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerPointArrangeAddin.Ribbon.ArrangeRibbonResources", typeof(ArrangeRibbonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-in se&amp;tting....
        /// </summary>
        public static string btnAddInSetting {
            get {
                return ResourceManager.GetString("btnAddInSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align &amp;bottom.
        /// </summary>
        public static string btnAlignBottom {
            get {
                return ResourceManager.GetString("btnAlignBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align &amp;center.
        /// </summary>
        public static string btnAlignCenter {
            get {
                return ResourceManager.GetString("btnAlignCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align &amp;left.
        /// </summary>
        public static string btnAlignLeft {
            get {
                return ResourceManager.GetString("btnAlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align &amp;middle.
        /// </summary>
        public static string btnAlignMiddle {
            get {
                return ResourceManager.GetString("btnAlignMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align and relative to the &amp;first object.
        /// </summary>
        public static string btnAlignRelative_ToFirstObject {
            get {
                return ResourceManager.GetString("btnAlignRelative_ToFirstObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align the selected &amp;objects.
        /// </summary>
        public static string btnAlignRelative_ToObjects {
            get {
                return ResourceManager.GetString("btnAlignRelative_ToObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Align and relative to the slide.
        /// </summary>
        public static string btnAlignRelative_ToSlide {
            get {
                return ResourceManager.GetString("btnAlignRelative_ToSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align &amp;right.
        /// </summary>
        public static string btnAlignRight {
            get {
                return ResourceManager.GetString("btnAlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align &amp;top.
        /// </summary>
        public static string btnAlignTop {
            get {
                return ResourceManager.GetString("btnAlignTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autofit off.
        /// </summary>
        public static string btnAutofitOff {
            get {
                return ResourceManager.GetString("btnAutofitOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize shape.
        /// </summary>
        public static string btnAutoResizeShape {
            get {
                return ResourceManager.GetString("btnAutoResizeShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shrink text.
        /// </summary>
        public static string btnAutoShrinkText {
            get {
                return ResourceManager.GetString("btnAutoShrinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy position.
        /// </summary>
        public static string btnCopyAudioPosition {
            get {
                return ResourceManager.GetString("btnCopyAudioPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy size.
        /// </summary>
        public static string btnCopyAudioSize {
            get {
                return ResourceManager.GetString("btnCopyAudioSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy position.
        /// </summary>
        public static string btnCopyChartPosition {
            get {
                return ResourceManager.GetString("btnCopyChartPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy size.
        /// </summary>
        public static string btnCopyChartSize {
            get {
                return ResourceManager.GetString("btnCopyChartSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy position.
        /// </summary>
        public static string btnCopyPicturePosition {
            get {
                return ResourceManager.GetString("btnCopyPicturePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy size.
        /// </summary>
        public static string btnCopyPictureSize {
            get {
                return ResourceManager.GetString("btnCopyPictureSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy position.
        /// </summary>
        public static string btnCopyShapePosition {
            get {
                return ResourceManager.GetString("btnCopyShapePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy size.
        /// </summary>
        public static string btnCopyShapeSize {
            get {
                return ResourceManager.GetString("btnCopyShapeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy position.
        /// </summary>
        public static string btnCopySmartartPosition {
            get {
                return ResourceManager.GetString("btnCopySmartartPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy size.
        /// </summary>
        public static string btnCopySmartartSize {
            get {
                return ResourceManager.GetString("btnCopySmartartSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy position.
        /// </summary>
        public static string btnCopyTablePosition {
            get {
                return ResourceManager.GetString("btnCopyTablePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy size.
        /// </summary>
        public static string btnCopyTableSize {
            get {
                return ResourceManager.GetString("btnCopyTableSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy position.
        /// </summary>
        public static string btnCopyVideoPosition {
            get {
                return ResourceManager.GetString("btnCopyVideoPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy size.
        /// </summary>
        public static string btnCopyVideoSize {
            get {
                return ResourceManager.GetString("btnCopyVideoSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribute &amp;horizontally.
        /// </summary>
        public static string btnDistributeHorizontal {
            get {
                return ResourceManager.GetString("btnDistributeHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribute &amp;vertically.
        /// </summary>
        public static string btnDistributeVertical {
            get {
                return ResourceManager.GetString("btnDistributeVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend to same &amp;bottom.
        /// </summary>
        public static string btnExtendSameBottom {
            get {
                return ResourceManager.GetString("btnExtendSameBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend to same &amp;left.
        /// </summary>
        public static string btnExtendSameLeft {
            get {
                return ResourceManager.GetString("btnExtendSameLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend to same &amp;right.
        /// </summary>
        public static string btnExtendSameRight {
            get {
                return ResourceManager.GetString("btnExtendSameRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend to same &amp;top.
        /// </summary>
        public static string btnExtendSameTop {
            get {
                return ResourceManager.GetString("btnExtendSameTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip &amp;horizontally.
        /// </summary>
        public static string btnFlipHorizontal {
            get {
                return ResourceManager.GetString("btnFlipHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip &amp;vertically.
        /// </summary>
        public static string btnFlipVertical {
            get {
                return ResourceManager.GetString("btnFlipVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Group shapes.
        /// </summary>
        public static string btnGroup {
            get {
                return ResourceManager.GetString("btnGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock aspect ratio.
        /// </summary>
        public static string btnLockAudioAspectRatio {
            get {
                return ResourceManager.GetString("btnLockAudioAspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock aspect ratio.
        /// </summary>
        public static string btnLockChartAspectRatio {
            get {
                return ResourceManager.GetString("btnLockChartAspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock aspect ratio.
        /// </summary>
        public static string btnLockPictureAspectRatio {
            get {
                return ResourceManager.GetString("btnLockPictureAspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock aspect ratio.
        /// </summary>
        public static string btnLockShapeAspectRatio {
            get {
                return ResourceManager.GetString("btnLockShapeAspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock aspect ratio.
        /// </summary>
        public static string btnLockSmartartAspectRatio {
            get {
                return ResourceManager.GetString("btnLockSmartartAspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock aspect ratio.
        /// </summary>
        public static string btnLockTableAspectRatio {
            get {
                return ResourceManager.GetString("btnLockTableAspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock aspect ratio.
        /// </summary>
        public static string btnLockVideoAspectRatio {
            get {
                return ResourceManager.GetString("btnLockVideoAspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to bac&amp;k.
        /// </summary>
        public static string btnMoveBack {
            get {
                return ResourceManager.GetString("btnMoveBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move &amp;backward.
        /// </summary>
        public static string btnMoveBackward {
            get {
                return ResourceManager.GetString("btnMoveBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move &amp;forward.
        /// </summary>
        public static string btnMoveForward {
            get {
                return ResourceManager.GetString("btnMoveForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to f&amp;ront.
        /// </summary>
        public static string btnMoveFront {
            get {
                return ResourceManager.GetString("btnMoveFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste position.
        /// </summary>
        public static string btnPasteAudioPosition {
            get {
                return ResourceManager.GetString("btnPasteAudioPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste size.
        /// </summary>
        public static string btnPasteAudioSize {
            get {
                return ResourceManager.GetString("btnPasteAudioSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste position.
        /// </summary>
        public static string btnPasteChartPosition {
            get {
                return ResourceManager.GetString("btnPasteChartPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste size.
        /// </summary>
        public static string btnPasteChartSize {
            get {
                return ResourceManager.GetString("btnPasteChartSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste position.
        /// </summary>
        public static string btnPastePicturePosition {
            get {
                return ResourceManager.GetString("btnPastePicturePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste size.
        /// </summary>
        public static string btnPastePictureSize {
            get {
                return ResourceManager.GetString("btnPastePictureSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste position.
        /// </summary>
        public static string btnPasteShapePosition {
            get {
                return ResourceManager.GetString("btnPasteShapePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste size.
        /// </summary>
        public static string btnPasteShapeSize {
            get {
                return ResourceManager.GetString("btnPasteShapeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste position.
        /// </summary>
        public static string btnPasteSmartartPosition {
            get {
                return ResourceManager.GetString("btnPasteSmartartPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste size.
        /// </summary>
        public static string btnPasteSmartartSize {
            get {
                return ResourceManager.GetString("btnPasteSmartartSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste position.
        /// </summary>
        public static string btnPasteTablePosition {
            get {
                return ResourceManager.GetString("btnPasteTablePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste size.
        /// </summary>
        public static string btnPasteTableSize {
            get {
                return ResourceManager.GetString("btnPasteTableSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste position.
        /// </summary>
        public static string btnPasteVideoPosition {
            get {
                return ResourceManager.GetString("btnPasteVideoPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste size.
        /// </summary>
        public static string btnPasteVideoSize {
            get {
                return ResourceManager.GetString("btnPasteVideoSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with clipboard.
        /// </summary>
        public static string btnReplaceWithClipboard {
            get {
                return ResourceManager.GetString("btnReplaceWithClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with file.
        /// </summary>
        public static string btnReplaceWithFile {
            get {
                return ResourceManager.GetString("btnReplaceWithFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset size.
        /// </summary>
        public static string btnResetAudioSize {
            get {
                return ResourceManager.GetString("btnResetAudioSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset horizontal margin.
        /// </summary>
        public static string btnResetHorizontalMargin {
            get {
                return ResourceManager.GetString("btnResetHorizontalMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset size.
        /// </summary>
        public static string btnResetPictureSize {
            get {
                return ResourceManager.GetString("btnResetPictureSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset vertical margin.
        /// </summary>
        public static string btnResetVerticalMargin {
            get {
                return ResourceManager.GetString("btnResetVerticalMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset size.
        /// </summary>
        public static string btnResetVideoSize {
            get {
                return ResourceManager.GetString("btnResetVideoSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate &amp;left with 90 degrees.
        /// </summary>
        public static string btnRotateLeft90 {
            get {
                return ResourceManager.GetString("btnRotateLeft90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate &amp;right with 90 degrees.
        /// </summary>
        public static string btnRotateRight90 {
            get {
                return ResourceManager.GetString("btnRotateRight90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale objects from botto&amp;m right.
        /// </summary>
        public static string btnScaleAnchor_BottomRight {
            get {
                return ResourceManager.GetString("btnScaleAnchor_BottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale objects &amp;from middle.
        /// </summary>
        public static string btnScaleAnchor_Middle {
            get {
                return ResourceManager.GetString("btnScaleAnchor_Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale &amp;objects from top left.
        /// </summary>
        public static string btnScaleAnchor_TopLeft {
            get {
                return ResourceManager.GetString("btnScaleAnchor_TopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale to same &amp;height as the first shape.
        /// </summary>
        public static string btnScaleSameHeight {
            get {
                return ResourceManager.GetString("btnScaleSameHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale to same &amp;size as the first shape.
        /// </summary>
        public static string btnScaleSameSize {
            get {
                return ResourceManager.GetString("btnScaleSameSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale to same &amp;width as the first shape.
        /// </summary>
        public static string btnScaleSameWidth {
            get {
                return ResourceManager.GetString("btnScaleSameWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap &amp;bottom to top.
        /// </summary>
        public static string btnSnapBottom {
            get {
                return ResourceManager.GetString("btnSnapBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap &amp;left to right.
        /// </summary>
        public static string btnSnapLeft {
            get {
                return ResourceManager.GetString("btnSnapLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap &amp;right to left.
        /// </summary>
        public static string btnSnapRight {
            get {
                return ResourceManager.GetString("btnSnapRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap &amp;top to bottom.
        /// </summary>
        public static string btnSnapTop {
            get {
                return ResourceManager.GetString("btnSnapTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Ungroup shapes.
        /// </summary>
        public static string btnUngroup {
            get {
                return ResourceManager.GetString("btnUngroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap text.
        /// </summary>
        public static string btnWrapText {
            get {
                return ResourceManager.GetString("btnWrapText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace to middle.
        /// </summary>
        public static string chkReplaceToMiddle {
            get {
                return ResourceManager.GetString("chkReplaceToMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve original size.
        /// </summary>
        public static string chkReserveOriginalSize {
            get {
                return ResourceManager.GetString("chkReserveOriginalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        public static string dlgAllFilesFilter {
            get {
                return ResourceManager.GetString("dlgAllFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image files.
        /// </summary>
        public static string dlgImageFilesFilter {
            get {
                return ResourceManager.GetString("dlgImageFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no picture in clipboard..
        /// </summary>
        public static string dlgNoPictureInClipboard {
            get {
                return ResourceManager.GetString("dlgNoPictureInClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace picture.
        /// </summary>
        public static string dlgReplacePicture {
            get {
                return ResourceManager.GetString("dlgReplacePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select picture for replacement.
        /// </summary>
        public static string dlgSelectPictureToReplace {
            get {
                return ResourceManager.GetString("dlgSelectPictureToReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal:.
        /// </summary>
        public static string edtAudioPositionX {
            get {
                return ResourceManager.GetString("edtAudioPositionX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical:.
        /// </summary>
        public static string edtAudioPositionY {
            get {
                return ResourceManager.GetString("edtAudioPositionY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal:.
        /// </summary>
        public static string edtChartPositionX {
            get {
                return ResourceManager.GetString("edtChartPositionX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical:.
        /// </summary>
        public static string edtChartPositionY {
            get {
                return ResourceManager.GetString("edtChartPositionY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom:.
        /// </summary>
        public static string edtMarginBottom {
            get {
                return ResourceManager.GetString("edtMarginBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left:.
        /// </summary>
        public static string edtMarginLeft {
            get {
                return ResourceManager.GetString("edtMarginLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right:.
        /// </summary>
        public static string edtMarginRight {
            get {
                return ResourceManager.GetString("edtMarginRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top:.
        /// </summary>
        public static string edtMarginTop {
            get {
                return ResourceManager.GetString("edtMarginTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal:.
        /// </summary>
        public static string edtPicturePositionX {
            get {
                return ResourceManager.GetString("edtPicturePositionX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical:.
        /// </summary>
        public static string edtPicturePositionY {
            get {
                return ResourceManager.GetString("edtPicturePositionY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal:.
        /// </summary>
        public static string edtShapePositionX {
            get {
                return ResourceManager.GetString("edtShapePositionX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical:.
        /// </summary>
        public static string edtShapePositionY {
            get {
                return ResourceManager.GetString("edtShapePositionY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal:.
        /// </summary>
        public static string edtSmartartPositionX {
            get {
                return ResourceManager.GetString("edtSmartartPositionX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical:.
        /// </summary>
        public static string edtSmartartPositionY {
            get {
                return ResourceManager.GetString("edtSmartartPositionY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal:.
        /// </summary>
        public static string edtTablePositionX {
            get {
                return ResourceManager.GetString("edtTablePositionX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical:.
        /// </summary>
        public static string edtTablePositionY {
            get {
                return ResourceManager.GetString("edtTablePositionY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal:.
        /// </summary>
        public static string edtVideoPositionX {
            get {
                return ResourceManager.GetString("edtVideoPositionX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical:.
        /// </summary>
        public static string edtVideoPositionY {
            get {
                return ResourceManager.GetString("edtVideoPositionY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrangement.
        /// </summary>
        public static string grpArrange {
            get {
                return ResourceManager.GetString("grpArrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size and position.
        /// </summary>
        public static string grpAudioSizeAndPosition {
            get {
                return ResourceManager.GetString("grpAudioSizeAndPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size and position.
        /// </summary>
        public static string grpChartSizeAndPosition {
            get {
                return ResourceManager.GetString("grpChartSizeAndPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size and position.
        /// </summary>
        public static string grpPictureSizeAndPosition {
            get {
                return ResourceManager.GetString("grpPictureSizeAndPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace picture.
        /// </summary>
        public static string grpReplacePicture {
            get {
                return ResourceManager.GetString("grpReplacePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size and position.
        /// </summary>
        public static string grpShapeSizeAndPosition {
            get {
                return ResourceManager.GetString("grpShapeSizeAndPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size and position.
        /// </summary>
        public static string grpSmartartSizeAndPosition {
            get {
                return ResourceManager.GetString("grpSmartartSizeAndPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size and position.
        /// </summary>
        public static string grpTableSizeAndPosition {
            get {
                return ResourceManager.GetString("grpTableSizeAndPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textbox.
        /// </summary>
        public static string grpTextbox {
            get {
                return ResourceManager.GetString("grpTextbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size and position.
        /// </summary>
        public static string grpVideoSizeAndPosition {
            get {
                return ResourceManager.GetString("grpVideoSizeAndPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word art.
        /// </summary>
        public static string grpWordArt {
            get {
                return ResourceManager.GetString("grpWordArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal margin:.
        /// </summary>
        public static string lblHorizontalMargin {
            get {
                return ResourceManager.GetString("lblHorizontalMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical margin:.
        /// </summary>
        public static string lblVerticalMargin {
            get {
                return ResourceManager.GetString("lblVerticalMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrange.
        /// </summary>
        public static string mnuArrangement {
            get {
                return ResourceManager.GetString("mnuArrangement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Alignment.
        /// </summary>
        public static string mnuArrangement_mnuAlignment {
            get {
                return ResourceManager.GetString("mnuArrangement_mnuAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Grouping.
        /// </summary>
        public static string mnuArrangement_mnuGrouping {
            get {
                return ResourceManager.GetString("mnuArrangement_mnuGrouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer order.
        /// </summary>
        public static string mnuArrangement_mnuLayerOrder {
            get {
                return ResourceManager.GetString("mnuArrangement_mnuLayerOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Resizing.
        /// </summary>
        public static string mnuArrangement_mnuResizing {
            get {
                return ResourceManager.GetString("mnuArrangement_mnuResizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R&amp;otation.
        /// </summary>
        public static string mnuArrangement_mnuRotation {
            get {
                return ResourceManager.GetString("mnuArrangement_mnuRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Snapping.
        /// </summary>
        public static string mnuArrangement_mnuSnapping {
            get {
                return ResourceManager.GetString("mnuArrangement_mnuSnapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-in setting.
        /// </summary>
        public static string mnuArrangement_sepAddInSetting {
            get {
                return ResourceManager.GetString("mnuArrangement_sepAddInSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object alignment and resizing.
        /// </summary>
        public static string mnuArrangement_sepAlignmentAndResizing {
            get {
                return ResourceManager.GetString("mnuArrangement_sepAlignmentAndResizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer order and grouping.
        /// </summary>
        public static string mnuArrangement_sepLayerOrderAndGrouping {
            get {
                return ResourceManager.GetString("mnuArrangement_sepLayerOrderAndGrouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects in the slide.
        /// </summary>
        public static string mnuArrangement_sepObjectsInSlide {
            get {
                return ResourceManager.GetString("mnuArrangement_sepObjectsInSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrange.
        /// </summary>
        public static string mnuAudioArrangement {
            get {
                return ResourceManager.GetString("mnuAudioArrangement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrange.
        /// </summary>
        public static string mnuChartArrangement {
            get {
                return ResourceManager.GetString("mnuChartArrangement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrange.
        /// </summary>
        public static string mnuPictureArrangement {
            get {
                return ResourceManager.GetString("mnuPictureArrangement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrange.
        /// </summary>
        public static string mnuShapeArrangement {
            get {
                return ResourceManager.GetString("mnuShapeArrangement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrange.
        /// </summary>
        public static string mnuSmartartArrangement {
            get {
                return ResourceManager.GetString("mnuSmartartArrangement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrange.
        /// </summary>
        public static string mnuTableArrangement {
            get {
                return ResourceManager.GetString("mnuTableArrangement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrange.
        /// </summary>
        public static string mnuVideoArrangement {
            get {
                return ResourceManager.GetString("mnuVideoArrangement", resourceCulture);
            }
        }
    }
}
