//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerPointArrangeAddin.Ribbon {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ArrangeRibbonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ArrangeRibbonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerPointArrangeAddin.Ribbon.ArrangeRibbonResources", typeof(ArrangeRibbonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-in se&amp;tting....
        /// </summary>
        public static string btnAddInSetting {
            get {
                return ResourceManager.GetString("btnAddInSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align &amp;bottom.
        /// </summary>
        public static string btnAlignBottom {
            get {
                return ResourceManager.GetString("btnAlignBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align &amp;center.
        /// </summary>
        public static string btnAlignCenter {
            get {
                return ResourceManager.GetString("btnAlignCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align &amp;left.
        /// </summary>
        public static string btnAlignLeft {
            get {
                return ResourceManager.GetString("btnAlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align &amp;middle.
        /// </summary>
        public static string btnAlignMiddle {
            get {
                return ResourceManager.GetString("btnAlignMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align and relative to the &amp;first object.
        /// </summary>
        public static string btnAlignRelative_ToFirstObject {
            get {
                return ResourceManager.GetString("btnAlignRelative_ToFirstObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align the selected &amp;objects.
        /// </summary>
        public static string btnAlignRelative_ToObjects {
            get {
                return ResourceManager.GetString("btnAlignRelative_ToObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Align and relative to the slide.
        /// </summary>
        public static string btnAlignRelative_ToSlide {
            get {
                return ResourceManager.GetString("btnAlignRelative_ToSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align &amp;right.
        /// </summary>
        public static string btnAlignRight {
            get {
                return ResourceManager.GetString("btnAlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align &amp;top.
        /// </summary>
        public static string btnAlignTop {
            get {
                return ResourceManager.GetString("btnAlignTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autofit off.
        /// </summary>
        public static string btnAutofitOff {
            get {
                return ResourceManager.GetString("btnAutofitOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize shape.
        /// </summary>
        public static string btnAutoResizeShape {
            get {
                return ResourceManager.GetString("btnAutoResizeShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shrink text.
        /// </summary>
        public static string btnAutoShrinkText {
            get {
                return ResourceManager.GetString("btnAutoShrinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy position.
        /// </summary>
        public static string btnCopyPosition {
            get {
                return ResourceManager.GetString("btnCopyPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy size.
        /// </summary>
        public static string btnCopySize {
            get {
                return ResourceManager.GetString("btnCopySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribute &amp;horizontally.
        /// </summary>
        public static string btnDistributeHorizontal {
            get {
                return ResourceManager.GetString("btnDistributeHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribute &amp;vertically.
        /// </summary>
        public static string btnDistributeVertical {
            get {
                return ResourceManager.GetString("btnDistributeVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend to same &amp;bottom.
        /// </summary>
        public static string btnExtendSameBottom {
            get {
                return ResourceManager.GetString("btnExtendSameBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend to same &amp;left.
        /// </summary>
        public static string btnExtendSameLeft {
            get {
                return ResourceManager.GetString("btnExtendSameLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend to same &amp;right.
        /// </summary>
        public static string btnExtendSameRight {
            get {
                return ResourceManager.GetString("btnExtendSameRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend to same &amp;top.
        /// </summary>
        public static string btnExtendSameTop {
            get {
                return ResourceManager.GetString("btnExtendSameTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip &amp;horizontally.
        /// </summary>
        public static string btnFlipHorizontal {
            get {
                return ResourceManager.GetString("btnFlipHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip &amp;vertically.
        /// </summary>
        public static string btnFlipVertical {
            get {
                return ResourceManager.GetString("btnFlipVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Group shapes.
        /// </summary>
        public static string btnGroup {
            get {
                return ResourceManager.GetString("btnGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock aspect ratio.
        /// </summary>
        public static string btnLockAspectRatio {
            get {
                return ResourceManager.GetString("btnLockAspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to bac&amp;k.
        /// </summary>
        public static string btnMoveBack {
            get {
                return ResourceManager.GetString("btnMoveBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move &amp;backward.
        /// </summary>
        public static string btnMoveBackward {
            get {
                return ResourceManager.GetString("btnMoveBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move &amp;forward.
        /// </summary>
        public static string btnMoveForward {
            get {
                return ResourceManager.GetString("btnMoveForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to f&amp;ront.
        /// </summary>
        public static string btnMoveFront {
            get {
                return ResourceManager.GetString("btnMoveFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste position.
        /// </summary>
        public static string btnPastePosition {
            get {
                return ResourceManager.GetString("btnPastePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste size.
        /// </summary>
        public static string btnPasteSize {
            get {
                return ResourceManager.GetString("btnPasteSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with clipboard.
        /// </summary>
        public static string btnReplaceWithClipboard {
            get {
                return ResourceManager.GetString("btnReplaceWithClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with file.
        /// </summary>
        public static string btnReplaceWithFile {
            get {
                return ResourceManager.GetString("btnReplaceWithFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset horizontal margin.
        /// </summary>
        public static string btnResetHorizontalMargin {
            get {
                return ResourceManager.GetString("btnResetHorizontalMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset size.
        /// </summary>
        public static string btnResetSize {
            get {
                return ResourceManager.GetString("btnResetSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset vertical margin.
        /// </summary>
        public static string btnResetVerticalMargin {
            get {
                return ResourceManager.GetString("btnResetVerticalMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate &amp;left with 90 degrees.
        /// </summary>
        public static string btnRotateLeft90 {
            get {
                return ResourceManager.GetString("btnRotateLeft90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate &amp;right with 90 degrees.
        /// </summary>
        public static string btnRotateRight90 {
            get {
                return ResourceManager.GetString("btnRotateRight90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale objects from botto&amp;m right.
        /// </summary>
        public static string btnScaleAnchor_BottomRight {
            get {
                return ResourceManager.GetString("btnScaleAnchor_BottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale objects &amp;from middle.
        /// </summary>
        public static string btnScaleAnchor_Middle {
            get {
                return ResourceManager.GetString("btnScaleAnchor_Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale &amp;objects from top left.
        /// </summary>
        public static string btnScaleAnchor_TopLeft {
            get {
                return ResourceManager.GetString("btnScaleAnchor_TopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale to same &amp;height as the first shape.
        /// </summary>
        public static string btnScaleSameHeight {
            get {
                return ResourceManager.GetString("btnScaleSameHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale to same &amp;size as the first shape.
        /// </summary>
        public static string btnScaleSameSize {
            get {
                return ResourceManager.GetString("btnScaleSameSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale to same &amp;width as the first shape.
        /// </summary>
        public static string btnScaleSameWidth {
            get {
                return ResourceManager.GetString("btnScaleSameWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap &amp;bottom to top.
        /// </summary>
        public static string btnSnapBottom {
            get {
                return ResourceManager.GetString("btnSnapBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap &amp;left to right.
        /// </summary>
        public static string btnSnapLeft {
            get {
                return ResourceManager.GetString("btnSnapLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap &amp;right to left.
        /// </summary>
        public static string btnSnapRight {
            get {
                return ResourceManager.GetString("btnSnapRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap &amp;top to bottom.
        /// </summary>
        public static string btnSnapTop {
            get {
                return ResourceManager.GetString("btnSnapTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Ungroup shapes.
        /// </summary>
        public static string btnUngroup {
            get {
                return ResourceManager.GetString("btnUngroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap text.
        /// </summary>
        public static string btnWrapText {
            get {
                return ResourceManager.GetString("btnWrapText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace to middle.
        /// </summary>
        public static string chkReplaceToMiddle {
            get {
                return ResourceManager.GetString("chkReplaceToMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve original size.
        /// </summary>
        public static string chkReserveOriginalSize {
            get {
                return ResourceManager.GetString("chkReserveOriginalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        public static string dlgAllFilesFilter {
            get {
                return ResourceManager.GetString("dlgAllFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image files.
        /// </summary>
        public static string dlgImageFilesFilter {
            get {
                return ResourceManager.GetString("dlgImageFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no picture in clipboard..
        /// </summary>
        public static string dlgNoPictureInClipboard {
            get {
                return ResourceManager.GetString("dlgNoPictureInClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace picture.
        /// </summary>
        public static string dlgReplacePicture {
            get {
                return ResourceManager.GetString("dlgReplacePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select picture for replacement.
        /// </summary>
        public static string dlgSelectPictureToReplace {
            get {
                return ResourceManager.GetString("dlgSelectPictureToReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom:.
        /// </summary>
        public static string edtMarginBottom {
            get {
                return ResourceManager.GetString("edtMarginBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left:.
        /// </summary>
        public static string edtMarginLeft {
            get {
                return ResourceManager.GetString("edtMarginLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right:.
        /// </summary>
        public static string edtMarginRight {
            get {
                return ResourceManager.GetString("edtMarginRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top:.
        /// </summary>
        public static string edtMarginTop {
            get {
                return ResourceManager.GetString("edtMarginTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal:.
        /// </summary>
        public static string edtPositionX {
            get {
                return ResourceManager.GetString("edtPositionX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical:.
        /// </summary>
        public static string edtPositionY {
            get {
                return ResourceManager.GetString("edtPositionY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrangement.
        /// </summary>
        public static string grpArrange {
            get {
                return ResourceManager.GetString("grpArrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace picture.
        /// </summary>
        public static string grpReplacePicture {
            get {
                return ResourceManager.GetString("grpReplacePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size and position.
        /// </summary>
        public static string grpSizeAndPosition {
            get {
                return ResourceManager.GetString("grpSizeAndPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textbox.
        /// </summary>
        public static string grpTextbox {
            get {
                return ResourceManager.GetString("grpTextbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word art.
        /// </summary>
        public static string grpWordArt {
            get {
                return ResourceManager.GetString("grpWordArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal margin:.
        /// </summary>
        public static string lblHorizontalMargin {
            get {
                return ResourceManager.GetString("lblHorizontalMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical margin:.
        /// </summary>
        public static string lblVerticalMargin {
            get {
                return ResourceManager.GetString("lblVerticalMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrange.
        /// </summary>
        public static string mnuArrangement {
            get {
                return ResourceManager.GetString("mnuArrangement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Alignment.
        /// </summary>
        public static string mnuArrangement_mnuAlignment {
            get {
                return ResourceManager.GetString("mnuArrangement_mnuAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Grouping.
        /// </summary>
        public static string mnuArrangement_mnuGrouping {
            get {
                return ResourceManager.GetString("mnuArrangement_mnuGrouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer order.
        /// </summary>
        public static string mnuArrangement_mnuLayerOrder {
            get {
                return ResourceManager.GetString("mnuArrangement_mnuLayerOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Resizing.
        /// </summary>
        public static string mnuArrangement_mnuResizing {
            get {
                return ResourceManager.GetString("mnuArrangement_mnuResizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R&amp;otation.
        /// </summary>
        public static string mnuArrangement_mnuRotation {
            get {
                return ResourceManager.GetString("mnuArrangement_mnuRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Snapping.
        /// </summary>
        public static string mnuArrangement_mnuSnapping {
            get {
                return ResourceManager.GetString("mnuArrangement_mnuSnapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-in setting.
        /// </summary>
        public static string mnuArrangement_sepAddInSetting {
            get {
                return ResourceManager.GetString("mnuArrangement_sepAddInSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object alignment and resizing.
        /// </summary>
        public static string mnuArrangement_sepAlignmentAndResizing {
            get {
                return ResourceManager.GetString("mnuArrangement_sepAlignmentAndResizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer order and grouping.
        /// </summary>
        public static string mnuArrangement_sepLayerOrderAndGrouping {
            get {
                return ResourceManager.GetString("mnuArrangement_sepLayerOrderAndGrouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects in the slide.
        /// </summary>
        public static string mnuArrangement_sepObjectsInSlide {
            get {
                return ResourceManager.GetString("mnuArrangement_sepObjectsInSlide", resourceCulture);
            }
        }
    }
}
