//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerPointArrangeAddin.Misc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MiscResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MiscResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerPointArrangeAddin.Misc.MiscResources", typeof(MiscResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AoiHosizora (https://github.com/Aoi-hosizora).
        /// </summary>
        internal static string Desc_Author {
            get {
                return ResourceManager.GetString("Desc_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string Desc_AuthorKey {
            get {
                return ResourceManager.GetString("Desc_AuthorKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Aoi-hosizora/PowerPointArrangeAddin.
        /// </summary>
        internal static string Desc_Homepage {
            get {
                return ResourceManager.GetString("Desc_Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage.
        /// </summary>
        internal static string Desc_HomepageKey {
            get {
                return ResourceManager.GetString("Desc_HomepageKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerPoint Arrangement Assistant Add-in.
        /// </summary>
        internal static string Desc_Title {
            get {
                return ResourceManager.GetString("Desc_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&quot;.
        /// </summary>
        internal static string Desc_TitleWrapper {
            get {
                return ResourceManager.GetString("Desc_TitleWrapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Desc_VersionKey {
            get {
                return ResourceManager.GetString("Desc_VersionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        internal static string Dlg_CheckUpdateProgressText {
            get {
                return ResourceManager.GetString("Dlg_CheckUpdateProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current version ({0}) is the newest version..
        /// </summary>
        internal static string Dlg_CurrentIsNewestVersionText {
            get {
                return ResourceManager.GetString("Dlg_CurrentIsNewestVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version of &quot;PowerPoint Arrangement Assistant Add-in&quot; you used currently is {0}..
        /// </summary>
        internal static string Dlg_CurrentVersionText {
            get {
                return ResourceManager.GetString("Dlg_CurrentVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable automatic &amp;checking.
        /// </summary>
        internal static string Dlg_DisableAutoCheckUpdateText {
            get {
                return ResourceManager.GetString("Dlg_DisableAutoCheckUpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to download the new version?.
        /// </summary>
        internal static string Dlg_DownloadNewVersionQuestionText {
            get {
                return ResourceManager.GetString("Dlg_DownloadNewVersionQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get release information..
        /// </summary>
        internal static string Dlg_GetReleaseFailedText {
            get {
                return ResourceManager.GetString("Dlg_GetReleaseFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version {0} has been released!.
        /// </summary>
        internal static string Dlg_HasNewVersionReleasedText {
            get {
                return ResourceManager.GetString("Dlg_HasNewVersionReleasedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore this &amp;version.
        /// </summary>
        internal static string Dlg_IgnoreThisVersion {
            get {
                return ResourceManager.GetString("Dlg_IgnoreThisVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore until &amp;tomorrow.
        /// </summary>
        internal static string Dlg_IgnoreUntilTomorrowText {
            get {
                return ResourceManager.GetString("Dlg_IgnoreUntilTomorrowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no updates available..
        /// </summary>
        internal static string Dlg_NoUpdateText {
            get {
                return ResourceManager.GetString("Dlg_NoUpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Note:.
        /// </summary>
        internal static string Dlg_ReleaseNoteText {
            get {
                return ResourceManager.GetString("Dlg_ReleaseNoteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit &amp;AppCenter to download.
        /// </summary>
        internal static string Dlg_VisitAppCenterText {
            get {
                return ResourceManager.GetString("Dlg_VisitAppCenterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit &amp;GitHub to download.
        /// </summary>
        internal static string Dlg_VisitGitHubText {
            get {
                return ResourceManager.GetString("Dlg_VisitGitHubText", resourceCulture);
            }
        }
    }
}
