//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerPointArrangeAddin.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool showWordArtGroup {
            get {
                return ((bool)(this["showWordArtGroup"]));
            }
            set {
                this["showWordArtGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool showArrangementGroup {
            get {
                return ((bool)(this["showArrangementGroup"]));
            }
            set {
                this["showArrangementGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool showReplacePictureGroup {
            get {
                return ((bool)(this["showReplacePictureGroup"]));
            }
            set {
                this["showReplacePictureGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool showShapeTextboxGroup {
            get {
                return ((bool)(this["showShapeTextboxGroup"]));
            }
            set {
                this["showShapeTextboxGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool showShapeSizeAndPositionGroup {
            get {
                return ((bool)(this["showShapeSizeAndPositionGroup"]));
            }
            set {
                this["showShapeSizeAndPositionGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool showPictureSizeAndPositionGroup {
            get {
                return ((bool)(this["showPictureSizeAndPositionGroup"]));
            }
            set {
                this["showPictureSizeAndPositionGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default")]
        public string language {
            get {
                return ((string)(this["language"]));
            }
            set {
                this["language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool showVideoSizeAndPositionGroup {
            get {
                return ((bool)(this["showVideoSizeAndPositionGroup"]));
            }
            set {
                this["showVideoSizeAndPositionGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool showAudioSizeAndPositionGroup {
            get {
                return ((bool)(this["showAudioSizeAndPositionGroup"]));
            }
            set {
                this["showAudioSizeAndPositionGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool showTableSizeAndPositionGroup {
            get {
                return ((bool)(this["showTableSizeAndPositionGroup"]));
            }
            set {
                this["showTableSizeAndPositionGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool showChartSizeAndPositionGroup {
            get {
                return ((bool)(this["showChartSizeAndPositionGroup"]));
            }
            set {
                this["showChartSizeAndPositionGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool showSmartArtSizeAndPositionGroup {
            get {
                return ((bool)(this["showSmartArtSizeAndPositionGroup"]));
            }
            set {
                this["showSmartArtSizeAndPositionGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool lessButtonsForArrangementGroup {
            get {
                return ((bool)(this["lessButtonsForArrangementGroup"]));
            }
            set {
                this["lessButtonsForArrangementGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool showSizeAndPositionGroup {
            get {
                return ((bool)(this["showSizeAndPositionGroup"]));
            }
            set {
                this["showSizeAndPositionGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hideMarginSettingForTextboxGroup {
            get {
                return ((bool)(this["hideMarginSettingForTextboxGroup"]));
            }
            set {
                this["hideMarginSettingForTextboxGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool checkUpdateWhenStartUp {
            get {
                return ((bool)(this["checkUpdateWhenStartUp"]));
            }
            set {
                this["checkUpdateWhenStartUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ignoreUpdateRecord {
            get {
                return ((string)(this["ignoreUpdateRecord"]));
            }
            set {
                this["ignoreUpdateRecord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2013")]
        public string iconStyle {
            get {
                return ((string)(this["iconStyle"]));
            }
            set {
                this["iconStyle"] = value;
            }
        }
    }
}
