//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ppt_arrange_addin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ArrangeRibbonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ArrangeRibbonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ppt_arrange_addin.ArrangeRibbonResources", typeof(ArrangeRibbonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align bottom.
        /// </summary>
        public static string btnAlignBottom {
            get {
                return ResourceManager.GetString("btnAlignBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align center.
        /// </summary>
        public static string btnAlignCenter {
            get {
                return ResourceManager.GetString("btnAlignCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align left.
        /// </summary>
        public static string btnAlignLeft {
            get {
                return ResourceManager.GetString("btnAlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align middle.
        /// </summary>
        public static string btnAlignMiddle {
            get {
                return ResourceManager.GetString("btnAlignMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align right.
        /// </summary>
        public static string btnAlignRight {
            get {
                return ResourceManager.GetString("btnAlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align top.
        /// </summary>
        public static string btnAlignTop {
            get {
                return ResourceManager.GetString("btnAlignTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribute horizontally.
        /// </summary>
        public static string btnDistributeHorizontal {
            get {
                return ResourceManager.GetString("btnDistributeHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribute vertically.
        /// </summary>
        public static string btnDistributeVertical {
            get {
                return ResourceManager.GetString("btnDistributeVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend to same bottom.
        /// </summary>
        public static string btnExtendSameBottom {
            get {
                return ResourceManager.GetString("btnExtendSameBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend to same left.
        /// </summary>
        public static string btnExtendSameLeft {
            get {
                return ResourceManager.GetString("btnExtendSameLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend to same right.
        /// </summary>
        public static string btnExtendSameRight {
            get {
                return ResourceManager.GetString("btnExtendSameRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend to same top.
        /// </summary>
        public static string btnExtendSameTop {
            get {
                return ResourceManager.GetString("btnExtendSameTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip horizontally.
        /// </summary>
        public static string btnFlipHorizontal {
            get {
                return ResourceManager.GetString("btnFlipHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip vertically.
        /// </summary>
        public static string btnFlipVertical {
            get {
                return ResourceManager.GetString("btnFlipVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group shapes.
        /// </summary>
        public static string btnGroup {
            get {
                return ResourceManager.GetString("btnGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to back.
        /// </summary>
        public static string btnMoveBack {
            get {
                return ResourceManager.GetString("btnMoveBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move backward.
        /// </summary>
        public static string btnMoveBackward {
            get {
                return ResourceManager.GetString("btnMoveBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move forward.
        /// </summary>
        public static string btnMoveForward {
            get {
                return ResourceManager.GetString("btnMoveForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to front.
        /// </summary>
        public static string btnMoveFront {
            get {
                return ResourceManager.GetString("btnMoveFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate left with 90 degrees.
        /// </summary>
        public static string btnRotateLeft90 {
            get {
                return ResourceManager.GetString("btnRotateLeft90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate right with 90 degrees.
        /// </summary>
        public static string btnRotateRight90 {
            get {
                return ResourceManager.GetString("btnRotateRight90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch from middle.
        /// </summary>
        public static string btnScalePosition_Middle {
            get {
                return ResourceManager.GetString("btnScalePosition_Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch from top left.
        /// </summary>
        public static string btnScalePosition_TopLeft {
            get {
                return ResourceManager.GetString("btnScalePosition_TopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch to same height.
        /// </summary>
        public static string btnScaleSameHeight {
            get {
                return ResourceManager.GetString("btnScaleSameHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch to same size.
        /// </summary>
        public static string btnScaleSameSize {
            get {
                return ResourceManager.GetString("btnScaleSameSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch to same width.
        /// </summary>
        public static string btnScaleSameWidth {
            get {
                return ResourceManager.GetString("btnScaleSameWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap to bottom.
        /// </summary>
        public static string btnSnapBottom {
            get {
                return ResourceManager.GetString("btnSnapBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap to left.
        /// </summary>
        public static string btnSnapLeft {
            get {
                return ResourceManager.GetString("btnSnapLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap to right.
        /// </summary>
        public static string btnSnapRight {
            get {
                return ResourceManager.GetString("btnSnapRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap to top.
        /// </summary>
        public static string btnSnapTop {
            get {
                return ResourceManager.GetString("btnSnapTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungroup shapes.
        /// </summary>
        public static string btnUngroup {
            get {
                return ResourceManager.GetString("btnUngroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrange.
        /// </summary>
        public static string grpArrange {
            get {
                return ResourceManager.GetString("grpArrange", resourceCulture);
            }
        }
    }
}
