//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ppt_arrange_addin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ArrangeRibbonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ArrangeRibbonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ppt_arrange_addin.ArrangeRibbonResources", typeof(ArrangeRibbonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-in setting....
        /// </summary>
        public static string btnAddInSetting {
            get {
                return ResourceManager.GetString("btnAddInSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align bottom.
        /// </summary>
        public static string btnAlignBottom {
            get {
                return ResourceManager.GetString("btnAlignBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align center.
        /// </summary>
        public static string btnAlignCenter {
            get {
                return ResourceManager.GetString("btnAlignCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align left.
        /// </summary>
        public static string btnAlignLeft {
            get {
                return ResourceManager.GetString("btnAlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align middle.
        /// </summary>
        public static string btnAlignMiddle {
            get {
                return ResourceManager.GetString("btnAlignMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align right.
        /// </summary>
        public static string btnAlignRight {
            get {
                return ResourceManager.GetString("btnAlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align top.
        /// </summary>
        public static string btnAlignTop {
            get {
                return ResourceManager.GetString("btnAlignTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autofit off.
        /// </summary>
        public static string btnAutofitOff {
            get {
                return ResourceManager.GetString("btnAutofitOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize shape.
        /// </summary>
        public static string btnAutoResizeShape {
            get {
                return ResourceManager.GetString("btnAutoResizeShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shrink text.
        /// </summary>
        public static string btnAutoShrinkText {
            get {
                return ResourceManager.GetString("btnAutoShrinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy position.
        /// </summary>
        public static string btnCopyPicturePosition {
            get {
                return ResourceManager.GetString("btnCopyPicturePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy size.
        /// </summary>
        public static string btnCopyPictureSize {
            get {
                return ResourceManager.GetString("btnCopyPictureSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy position.
        /// </summary>
        public static string btnCopyShapePosition {
            get {
                return ResourceManager.GetString("btnCopyShapePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy size.
        /// </summary>
        public static string btnCopyShapeSize {
            get {
                return ResourceManager.GetString("btnCopyShapeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribute horizontally.
        /// </summary>
        public static string btnDistributeHorizontal {
            get {
                return ResourceManager.GetString("btnDistributeHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribute vertically.
        /// </summary>
        public static string btnDistributeVertical {
            get {
                return ResourceManager.GetString("btnDistributeVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend to same bottom.
        /// </summary>
        public static string btnExtendSameBottom {
            get {
                return ResourceManager.GetString("btnExtendSameBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend to same left.
        /// </summary>
        public static string btnExtendSameLeft {
            get {
                return ResourceManager.GetString("btnExtendSameLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend to same right.
        /// </summary>
        public static string btnExtendSameRight {
            get {
                return ResourceManager.GetString("btnExtendSameRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend to same top.
        /// </summary>
        public static string btnExtendSameTop {
            get {
                return ResourceManager.GetString("btnExtendSameTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip horizontally.
        /// </summary>
        public static string btnFlipHorizontal {
            get {
                return ResourceManager.GetString("btnFlipHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip vertically.
        /// </summary>
        public static string btnFlipVertical {
            get {
                return ResourceManager.GetString("btnFlipVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group shapes.
        /// </summary>
        public static string btnGroup {
            get {
                return ResourceManager.GetString("btnGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock aspect ratio.
        /// </summary>
        public static string btnLockPictureAspectRatio {
            get {
                return ResourceManager.GetString("btnLockPictureAspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock aspect ratio.
        /// </summary>
        public static string btnLockShapeAspectRatio {
            get {
                return ResourceManager.GetString("btnLockShapeAspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to back.
        /// </summary>
        public static string btnMoveBack {
            get {
                return ResourceManager.GetString("btnMoveBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move backward.
        /// </summary>
        public static string btnMoveBackward {
            get {
                return ResourceManager.GetString("btnMoveBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move forward.
        /// </summary>
        public static string btnMoveForward {
            get {
                return ResourceManager.GetString("btnMoveForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to front.
        /// </summary>
        public static string btnMoveFront {
            get {
                return ResourceManager.GetString("btnMoveFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste position.
        /// </summary>
        public static string btnPastePicturePosition {
            get {
                return ResourceManager.GetString("btnPastePicturePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste size.
        /// </summary>
        public static string btnPastePictureSize {
            get {
                return ResourceManager.GetString("btnPastePictureSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste position.
        /// </summary>
        public static string btnPasteShapePosition {
            get {
                return ResourceManager.GetString("btnPasteShapePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste size.
        /// </summary>
        public static string btnPasteShapeSize {
            get {
                return ResourceManager.GetString("btnPasteShapeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with clipboard.
        /// </summary>
        public static string btnReplaceWithClipboard {
            get {
                return ResourceManager.GetString("btnReplaceWithClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with file.
        /// </summary>
        public static string btnReplaceWithFile {
            get {
                return ResourceManager.GetString("btnReplaceWithFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset horizontal margin.
        /// </summary>
        public static string btnResetHorizontalMargin {
            get {
                return ResourceManager.GetString("btnResetHorizontalMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset size.
        /// </summary>
        public static string btnResetPictureSize {
            get {
                return ResourceManager.GetString("btnResetPictureSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset vertical margin.
        /// </summary>
        public static string btnResetVerticalMargin {
            get {
                return ResourceManager.GetString("btnResetVerticalMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate left with 90 degrees.
        /// </summary>
        public static string btnRotateLeft90 {
            get {
                return ResourceManager.GetString("btnRotateLeft90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate right with 90 degrees.
        /// </summary>
        public static string btnRotateRight90 {
            get {
                return ResourceManager.GetString("btnRotateRight90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale objects from middle.
        /// </summary>
        public static string btnScaleAnchor_Middle {
            get {
                return ResourceManager.GetString("btnScaleAnchor_Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale objects from top left.
        /// </summary>
        public static string btnScaleAnchor_TopLeft {
            get {
                return ResourceManager.GetString("btnScaleAnchor_TopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale to same height (as the first shape).
        /// </summary>
        public static string btnScaleSameHeight {
            get {
                return ResourceManager.GetString("btnScaleSameHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale to same size (as the first shape).
        /// </summary>
        public static string btnScaleSameSize {
            get {
                return ResourceManager.GetString("btnScaleSameSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale to same width (as the first shape).
        /// </summary>
        public static string btnScaleSameWidth {
            get {
                return ResourceManager.GetString("btnScaleSameWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap to bottom.
        /// </summary>
        public static string btnSnapBottom {
            get {
                return ResourceManager.GetString("btnSnapBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap to left.
        /// </summary>
        public static string btnSnapLeft {
            get {
                return ResourceManager.GetString("btnSnapLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap to right.
        /// </summary>
        public static string btnSnapRight {
            get {
                return ResourceManager.GetString("btnSnapRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap to top.
        /// </summary>
        public static string btnSnapTop {
            get {
                return ResourceManager.GetString("btnSnapTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungroup shapes.
        /// </summary>
        public static string btnUngroup {
            get {
                return ResourceManager.GetString("btnUngroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap text.
        /// </summary>
        public static string btnWrapText {
            get {
                return ResourceManager.GetString("btnWrapText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace to middle.
        /// </summary>
        public static string chkReplaceToMiddle {
            get {
                return ResourceManager.GetString("chkReplaceToMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve original size.
        /// </summary>
        public static string chkReserveOriginalSize {
            get {
                return ResourceManager.GetString("chkReserveOriginalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        public static string dlgAllFilesFilter {
            get {
                return ResourceManager.GetString("dlgAllFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image files.
        /// </summary>
        public static string dlgImageFilesFilter {
            get {
                return ResourceManager.GetString("dlgImageFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no picture in clipboard..
        /// </summary>
        public static string dlgNoPictureInClipboard {
            get {
                return ResourceManager.GetString("dlgNoPictureInClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace picture.
        /// </summary>
        public static string dlgReplacePicture {
            get {
                return ResourceManager.GetString("dlgReplacePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select picture for replacement.
        /// </summary>
        public static string dlgSelectPictureToReplace {
            get {
                return ResourceManager.GetString("dlgSelectPictureToReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom margin:.
        /// </summary>
        public static string edtMarginBottom {
            get {
                return ResourceManager.GetString("edtMarginBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left margin:.
        /// </summary>
        public static string edtMarginLeft {
            get {
                return ResourceManager.GetString("edtMarginLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right margin:.
        /// </summary>
        public static string edtMarginRight {
            get {
                return ResourceManager.GetString("edtMarginRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top margin:.
        /// </summary>
        public static string edtMarginTop {
            get {
                return ResourceManager.GetString("edtMarginTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal:.
        /// </summary>
        public static string edtPicturePositionX {
            get {
                return ResourceManager.GetString("edtPicturePositionX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical:.
        /// </summary>
        public static string edtPicturePositionY {
            get {
                return ResourceManager.GetString("edtPicturePositionY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal:.
        /// </summary>
        public static string edtShapePositionX {
            get {
                return ResourceManager.GetString("edtShapePositionX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical:.
        /// </summary>
        public static string edtShapePositionY {
            get {
                return ResourceManager.GetString("edtShapePositionY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrange.
        /// </summary>
        public static string grpArrange {
            get {
                return ResourceManager.GetString("grpArrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size and position.
        /// </summary>
        public static string grpPictureSizeAndPosition {
            get {
                return ResourceManager.GetString("grpPictureSizeAndPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace picture.
        /// </summary>
        public static string grpReplacePicture {
            get {
                return ResourceManager.GetString("grpReplacePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size and position.
        /// </summary>
        public static string grpShapeSizeAndPosition {
            get {
                return ResourceManager.GetString("grpShapeSizeAndPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textbox.
        /// </summary>
        public static string grpTextbox {
            get {
                return ResourceManager.GetString("grpTextbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word art.
        /// </summary>
        public static string grpWordArt {
            get {
                return ResourceManager.GetString("grpWordArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrangement.
        /// </summary>
        public static string mnuArrangement {
            get {
                return ResourceManager.GetString("mnuArrangement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        public static string mnuArrangement_mnuAlignment {
            get {
                return ResourceManager.GetString("mnuArrangement_mnuAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouping.
        /// </summary>
        public static string mnuArrangement_mnuGrouping {
            get {
                return ResourceManager.GetString("mnuArrangement_mnuGrouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer order.
        /// </summary>
        public static string mnuArrangement_mnuLayerOrder {
            get {
                return ResourceManager.GetString("mnuArrangement_mnuLayerOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resizing.
        /// </summary>
        public static string mnuArrangement_mnuResizing {
            get {
                return ResourceManager.GetString("mnuArrangement_mnuResizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation.
        /// </summary>
        public static string mnuArrangement_mnuRotation {
            get {
                return ResourceManager.GetString("mnuArrangement_mnuRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapping.
        /// </summary>
        public static string mnuArrangement_mnuSnapping {
            get {
                return ResourceManager.GetString("mnuArrangement_mnuSnapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-in setting.
        /// </summary>
        public static string mnuArrangement_sepAddInSetting {
            get {
                return ResourceManager.GetString("mnuArrangement_sepAddInSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object alignment and resizing.
        /// </summary>
        public static string mnuArrangement_sepAlignmentAndResizing {
            get {
                return ResourceManager.GetString("mnuArrangement_sepAlignmentAndResizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer order and grouping.
        /// </summary>
        public static string mnuArrangement_sepLayerOrderAndGrouping {
            get {
                return ResourceManager.GetString("mnuArrangement_sepLayerOrderAndGrouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects in the slide.
        /// </summary>
        public static string mnuArrangement_sepObjectsInSlide {
            get {
                return ResourceManager.GetString("mnuArrangement_sepObjectsInSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrangement.
        /// </summary>
        public static string mnuPictureArrangement {
            get {
                return ResourceManager.GetString("mnuPictureArrangement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrangement.
        /// </summary>
        public static string mnuShapeArrangement {
            get {
                return ResourceManager.GetString("mnuShapeArrangement", resourceCulture);
            }
        }
    }
}
